<a href="https://colab.research.google.com/github/guimonteiro31/exerc-cios-Coleta-e-Transforma-o-de-Dados-com-IA/blob/main/Criando_campos_derivados_com_Python_e_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io # Importar StringIO

url = 'https://pt.wikipedia.org/wiki/Lista_de_presidentes_do_Brasil'

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

try:
    response = requests.get(url, headers=headers)
    response.raise_for_status() # Lança um erro para status de requisição HTTP ruins (4xx ou 5xx)

    # Passar o conteúdo HTML bruto para pd.read_html. Isso é mais robusto para tabelas complexas.
    tables = pd.read_html(io.StringIO(response.text)) # Usar StringIO para conteúdo HTML literal

    df = None
    found_president_col = False # Flag para indicar se uma coluna de presidente foi encontrada

    # Iterar sobre os DataFrames para encontrar a tabela correta
    for i, table_df in enumerate(tables):
        print(f"--- Verificando tabela {i} ---")
        print("Colunas encontradas:", table_df.columns.tolist()) # Imprimir colunas para inspeção

        # Verificar a existência de 'Presidente' em várias formas
        for col_name in table_df.columns:
            # Lidar com colunas de multi-índice (tuplas)
            if isinstance(col_name, tuple):
                # Aplanar os componentes da tupla para correspondência de string
                col_name_str = ' '.join(filter(None, [str(c) for c in col_name])).lower()
            else:
                col_name_str = str(col_name).lower()

            if 'presidente' in col_name_str:
                df = table_df
                found_president_col = True
                print(f"Tabela de presidentes encontrada no índice {i} com coluna contendo: '{col_name}'.")
                display(df.head())
                break # Sair do loop interno assim que a coluna de presidente for encontrada

        if found_president_col:
            break # Sair do loop externo assim que a tabela correta for encontrada

    if df is None:
        print("Não foi possível encontrar a tabela de presidentes na página.")
    else:
        print("DataFrame com a lista de presidentes (poderá necessitar de ajuste de colunas):")
        display(df.head())


except requests.exceptions.RequestException as e:
    print(f"Ocorreu um erro na requisição HTTP: {e}")
except Exception as e:
    print(f"Ocorreu um erro geral ao tentar ler as tabelas: {e}")

--- Verificando tabela 0 ---
Colunas encontradas: [('N.°', 'Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40\xa0anos, 11\xa0meses e 9\xa0dias)'), ('Presidente (nascimento–morte)', 'Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40\xa0anos, 11\xa0meses e 9\xa0dias)'), ('Fotografia', 'Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40\xa0anos, 11\xa0meses e 9\xa0dias)'), ('Período do mandato (duração do mandato)', 'Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40\xa0anos, 11\xa0meses e 9\xa0dias)'), ('Partido', 'Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40\xa0anos, 11\xa0meses e 9\xa0dias)'), ('Vice-presidente', 'Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40\xa0anos, 11\xa0meses e 9\xa0dias)'), ('Eleição', 'Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40\xa0anos, 11\xa0meses e 9\xa0dias)'), ('Notas e referências', 'Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40\xa0anos, 11\xa0meses e 9\xa0dias)')]
Tabela de presidentes encontrada no índice 0 com coluna contendo: '('Presidente (nascimento–morte)', 'Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40\xa0anos, 11\xa0meses e 9\xa0dias)')'.

,N.°,Presidente (nascimento–morte),Fotografia,Período do mandato (duração do mandato),Partido,Vice-presidente,Eleição,Notas e referências
,"Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)"
0,1,Deodoro da Fonseca (1827–1892),NaN,15 de novembro de 1889 – 23 de novembro de 189...,Nenhum,Cargo inexistente [nota 2],Proclamação de 1889,[nota 3] [4][5][6]
1,1,Deodoro da Fonseca (1827–1892),NaN,15 de novembro de 1889 – 23 de novembro de 189...,Nenhum,Floriano Peixoto [nota 4],1891,[nota 3] [4][5][6]
2,2,Floriano Peixoto (1839–1895),NaN,23 de novembro de 1891 – 15 de novembro de 189...,Nenhum,Cargo vago,—,[nota 5] [8][9]
3,3,Prudente de Morais (1841–1902),NaN,15 de novembro de 1894 – 15 de novembro de 189...,PR Federal,Manuel Vitorino,1894,[nota 6] [10][11]
4,4,Campos Sales (1841–1913),NaN,15 de novembro de 1898 – 15 de novembro de 190...,PRP,Rosa e Silva,1898,[12][13]

DataFrame com a lista de presidentes (poderá necessitar de ajuste de colunas):

,N.°,Presidente (nascimento–morte),Fotografia,Período do mandato (duração do mandato),Partido,Vice-presidente,Eleição,Notas e referências
,"Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)","Primeira República (República Velha ou Oligárquica) (15 de novembro de 1889 a 24 de outubro de 1930 – 40 anos, 11 meses e 9 dias)"
0,1,Deodoro da Fonseca (1827–1892),NaN,15 de novembro de 1889 – 23 de novembro de 189...,Nenhum,Cargo inexistente [nota 2],Proclamação de 1889,[nota 3] [4][5][6]
1,1,Deodoro da Fonseca (1827–1892),NaN,15 de novembro de 1889 – 23 de novembro de 189...,Nenhum,Floriano Peixoto [nota 4],1891,[nota 3] [4][5][6]
2,2,Floriano Peixoto (1839–1895),NaN,23 de novembro de 1891 – 15 de novembro de 189...,Nenhum,Cargo vago,—,[nota 5] [8][9]
3,3,Prudente de Morais (1841–1902),NaN,15 de novembro de 1894 – 15 de novembro de 189...,PR Federal,Manuel Vitorino,1894,[nota 6] [10][11]
4,4,Campos Sales (1841–1913),NaN,15 de novembro de 1898 – 15 de novembro de 190...,PRP,Rosa e Silva,1898,[12][13]

Com a tabela extraída, o primeiro passo é limpar os nomes das colunas. As colunas estão em um formato de multi-índice, o que pode dificultar a manipulação. Vamos simplificá-las para que fiquem mais acessíveis.

In [25]:
import re # Ensure re is imported for regex operations

# Re-initialize df with the correct table from the 'tables' list (identified in f5ccf19b as index 0)
df = tables[0]

# Limpar os nomes das colunas

print(f"DEBUG: Initial df columns: {df.columns.tolist()}\n")

# 1. Aplanar o MultiIndex de forma robusta
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)
    print(f"DEBUG: df columns after flattening MultiIndex: {df.columns.tolist()}\n")
else:
    print(f"DEBUG: df columns was not MultiIndex, current: {df.columns.tolist()}\n")

# 2. Limpar strings de nomes de colunas (remover conteúdo entre parênteses e espaços extras)
new_columns_step2 = []
for col_name in df.columns:
    cleaned_name = re.sub(r'\s*\(.*\)', '', str(col_name)).strip()
    new_columns_step2.append(cleaned_name)
df.columns = new_columns_step2
print(f"DEBUG: df columns after string cleaning (removing parenthesis content): {df.columns.tolist()}\n")

# 3. Renomear as colunas para termos nomes finais mais simples e consistentes
# O mapeamento considera os nomes exatos esperados após o passo 2 e os novos nomes desejados.
column_rename_map = {
    'N.°': 'Numero',
    'Presidente': 'Presidente',
    'Período do mandato': 'Periodo_Mandato',
    'Fotografia': 'Fotografia',
    'Partido': 'Partido',
    'Vice-presidente': 'Vice_Presidente',
    'Eleição': 'Eleicao',
    'Notas e referências': 'Notas_Referencias'
}

# Aplicar o renomeamento para as colunas que existem no DataFrame após o passo 2
df = df.rename(columns={old_name: new_name for old_name, new_name in column_rename_map.items() if old_name in df.columns})
print(f"DEBUG: df columns after final renaming step: {df.columns.tolist()}\n")

# 4. Filtrar e selecionar apenas as colunas que realmente precisamos
final_desired_columns = ['Numero', 'Presidente', 'Periodo_Mandato', 'Partido', 'Vice_Presidente', 'Eleicao']

# Filtrar o DataFrame para manter apenas as colunas desejadas que existam após o renomeamento
df = df.filter(items=final_desired_columns)
print(f"DEBUG: df columns after final filtering: {df.columns.tolist()}\n")

# Exibir as novas colunas e as primeiras linhas do DataFrame limpo
print("Colunas do DataFrame após limpeza e seleção final:")
print(df.columns.tolist())
print("DataFrame após limpeza das colunas:")
display(df.head())

DEBUG: Initial df columns: ['N.°', 'Presidente (nascimento–morte)', 'Fotografia', 'Período do mandato (duração do mandato)', 'Partido', 'Vice-presidente', 'Eleição', 'Notas e referências']

DEBUG: df columns was not MultiIndex, current: ['N.°', 'Presidente (nascimento–morte)', 'Fotografia', 'Período do mandato (duração do mandato)', 'Partido', 'Vice-presidente', 'Eleição', 'Notas e referências']

DEBUG: df columns after string cleaning (removing parenthesis content): ['N.°', 'Presidente', 'Fotografia', 'Período do mandato', 'Partido', 'Vice-presidente', 'Eleição', 'Notas e referências']

DEBUG: df columns after final renaming step: ['Numero', 'Presidente', 'Fotografia', 'Periodo_Mandato', 'Partido', 'Vice_Presidente', 'Eleicao', 'Notas_Referencias']

DEBUG: df columns after final filtering: ['Numero', 'Presidente', 'Periodo_Mandato', 'Partido', 'Vice_Presidente', 'Eleicao']

Colunas do DataFrame após limpeza e seleção final:
['Numero', 'Presidente', 'Periodo_Mandato', 'Partido', 'Vice_Presidente', 'Eleicao']
DataFrame após limpeza das colunas:

,Numero,Presidente,Periodo_Mandato,Partido,Vice_Presidente,Eleicao
0,1,Deodoro da Fonseca (1827–1892),15 de novembro de 1889 – 23 de novembro de 189...,Nenhum,Cargo inexistente [nota 2],Proclamação de 1889
1,1,Deodoro da Fonseca (1827–1892),15 de novembro de 1889 – 23 de novembro de 189...,Nenhum,Floriano Peixoto [nota 4],1891
2,2,Floriano Peixoto (1839–1895),23 de novembro de 1891 – 15 de novembro de 189...,Nenhum,Cargo vago,—
3,3,Prudente de Morais (1841–1902),15 de novembro de 1894 – 15 de novembro de 189...,PR Federal,Manuel Vitorino,1894
4,4,Campos Sales (1841–1913),15 de novembro de 1898 – 15 de novembro de 190...,PRP,Rosa e Silva,1898

Agora que as colunas estão limpas, precisamos extrair o ano de início do mandato da coluna `Periodo_Mandato`. Essa coluna contém informações de data e duração, e nosso objetivo é obter apenas o ano para calcular a década. Também vamos extrair o nome do presidente de forma mais limpa.

In [26]:
# Extrair o ano de início do mandato
def extract_start_year(periodo_mandato):
    if pd.isna(periodo_mandato):
        return None
    # Tenta encontrar um padrão como 'dia de mês de ANO' no início da string
    import re
    match = re.search(r'\d{1,2}\s+de\s+\w+\s+de\s+(\d{4})', periodo_mandato)
    if match:
        return int(match.group(1))
    # Se não encontrar, tenta encontrar o primeiro número de 4 dígitos
    match = re.search(r'(\d{4})', periodo_mandato)
    if match:
        return int(match.group(1))
    return None

# Adicionar uma verificação de coluna para robustez
periodo_col_name = None
if 'Periodo_Mandato' in df.columns:
    periodo_col_name = 'Periodo_Mandato'
elif 'Período do mandato' in df.columns:
    periodo_col_name = 'Período do mandato'

if periodo_col_name:
    df['Ano_Inicio'] = df[periodo_col_name].apply(extract_start_year)
else:
    print("Erro: Nenhuma das colunas 'Periodo_Mandato' ou 'Período do mandato' foi encontrada.")
    df['Ano_Inicio'] = None # Definir como None ou NaN para evitar erros posteriores

# Limpar o nome do presidente, removendo o que está entre parênteses e espaços extras
def clean_president_name(name):
    if pd.isna(name):
        return None
    import re
    cleaned_name = re.sub(r'\s*\(.*\)', '', name).strip()
    # Algumas entradas repetem o nome com informações adicionais, vamos pegar apenas o primeiro nome
    return cleaned_name.split('\n')[0].strip()

df['Presidente_Limpo'] = df['Presidente'].apply(clean_president_name)

# Remover linhas completamente duplicadas (mantendo o primeiro mandato)
# Isso ajuda a evitar contagens duplas para presidentes que apareceram mais de uma vez na mesma linha na tabela original
df_cleaned = df.drop_duplicates(subset=['Presidente_Limpo', 'Ano_Inicio', periodo_col_name])

# Filtrar e reorganizar as colunas conforme solicitado pelo usuário
final_selected_columns = ['Presidente_Limpo', periodo_col_name, 'Ano_Inicio']
df_cleaned = df_cleaned[final_selected_columns]

# Exibir as colunas relevantes e as primeiras linhas do DataFrame com os anos e nomes limpos
print("DataFrame com Ano_Inicio e Presidente_Limpo:")
display(df_cleaned.head(10))

DataFrame com Ano_Inicio e Presidente_Limpo:

,Presidente_Limpo,Periodo_Mandato,Ano_Inicio
0,Deodoro da Fonseca,15 de novembro de 1889 – 23 de novembro de 189...,1889.0
2,Floriano Peixoto,23 de novembro de 1891 – 15 de novembro de 189...,1891.0
3,Prudente de Morais,15 de novembro de 1894 – 15 de novembro de 189...,1894.0
4,Campos Sales,15 de novembro de 1898 – 15 de novembro de 190...,1898.0
5,Rodrigues Alves,15 de novembro de 1902 – 15 de novembro de 190...,1902.0
6,Afonso Pena,15 de novembro de 1906 – 14 de junho de 1909 (...,1906.0
7,Nilo Peçanha,14 de junho de 1909 – 15 de novembro de 1910 (...,1909.0
8,Hermes da Fonseca,15 de novembro de 1910 – 15 de novembro de 191...,1910.0
9,Venceslau Brás,15 de novembro de 1914 – 15 de novembro de 191...,1914.0
10,Rodrigues Alves,Morreu antes de tomar posse,NaN

Agora que temos os anos de início dos mandatos, podemos criar a coluna da década e agrupar os presidentes para obter as tabelas solicitadas.

In [24]:
# Criar a coluna 'Decada'
df_cleaned['Decada'] = (df_cleaned['Ano_Inicio'] // 10) * 10

# Tabela 1: Presidentes agrupados por década
# Vamos criar uma lista de presidentes para cada década
presidentes_por_decada = df_cleaned.groupby('Decada')['Presidente_Limpo'].apply(lambda x: list(set(x.dropna()))).reset_index()
print("### Presidentes agrupados por Década ###")
display(presidentes_por_decada)

# Tabela 2: Contagem de vezes que sofreram presidentes (contagem de mandatos)
# Assumindo que cada linha única de Presidente_Limpo e Ano_Inicio representa um mandato distinto
contagem_mandatos = df_cleaned.groupby('Presidente_Limpo').size().reset_index(name='Numero_Mandatos')
contagem_mandatos = contagem_mandatos.sort_values(by='Numero_Mandatos', ascending=False)
print("\n### Contagem de Mandatos por Presidente ###")
display(contagem_mandatos.head(10))

### Presidentes agrupados por Década ###

    Decada                                   Presidente_Limpo
0   1880.0                               [Deodoro da Fonseca]
1   1890.0  [Floriano Peixoto, Prudente de Morais, Campos ...
2   1900.0       [Nilo Peçanha, Rodrigues Alves, Afonso Pena]
3   1910.0  [Delfim Moreira, Venceslau Brás, Epitácio Pess...
4   1920.0                 [Artur Bernardes, Washington Luís]
5   1930.0  [Júlio Prestes, Getúlio Vargas, Junta Governat...
6   1940.0    [José Linhares, Quarta República, Gaspar Dutra]
7   1950.0  [Nereu Ramos, Carlos Luz, Café Filho, Getúlio ...
8   1960.0  [Castelo Branco, Quinta República, Pedro Aleix...
9   1970.0                  [Ernesto Geisel, João Figueiredo]
10  1980.0                     [José Sarney, Sexta República]
11  1990.0  [Fernando Henrique Cardoso, Itamar Franco, Fer...
12  2000.0                        [Luiz Inácio Lula da Silva]
13  2010.0     [Michel Temer, Dilma Rousseff, Jair Bolsonaro]
14  2020.0                        [Luiz Inácio Lula da Silva]

### Contagem de Mandatos por Presidente ###

             Presidente_Limpo  Numero_Mandatos
17             Getúlio Vargas                3
39            Rodrigues Alves                2
30  Luiz Inácio Lula da Silva                2
38           Ranieri Mazzilli                2
0                 Afonso Pena                1
1             Artur Bernardes                1
6               Costa e Silva                1
7              Delfim Moreira                1
8          Deodoro da Fonseca                1
9              Dilma Rousseff                1